name: install

on:
  push:
  pull_request:

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }} - ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        py:
          - "3.11"
          - "3.10"
          - "3.9"
        env:
          - pip
          - conda
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Conda
        if: matrix.env == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.py }}
          miniconda-version: "latest"
          activate-environment: test-env
          auto-update-conda: true

      - name: Setup Python for pip
        if: matrix.env == 'pip'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Upgrade pip
        run: python -m ensurepip --upgrade

      - name: Install pufferlib
        run: pip install -e .
